// Copyright (C) 2024 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: cts/tests/mediapc/requirements/mpc.proto

package mpc_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The  Media Performance class of a device.
//
// Media performance class are defined for each Android version starting with R
// (version 30). The special value of 0 designates that the device is not of a
// media performance class.
type MediaPerformanceClass int32

const (
	MediaPerformanceClass_MEDIA_PERFORMANCE_CLASS_UNSPECIFIED MediaPerformanceClass = 0
	MediaPerformanceClass_MEDIA_PERFORMANCE_CLASS_INVALID     MediaPerformanceClass = -1
	// As specified in
	// https://source.android.com/docs/compatibility/11/android-11-cdd#227_handheld_media_performance_class
	MediaPerformanceClass_MEDIA_PERFORMANCE_CLASS_11 MediaPerformanceClass = 30
	// As specified in
	// https://source.android.com/docs/compatibility/12/android-12-cdd#227_handheld_media_performance_class
	MediaPerformanceClass_MEDIA_PERFORMANCE_CLASS_12 MediaPerformanceClass = 31
	// As specified in
	// https://source.android.com/docs/compatibility/13/android-13-cdd#227_handheld_media_performance_class
	MediaPerformanceClass_MEDIA_PERFORMANCE_CLASS_13 MediaPerformanceClass = 33
	// As specified in
	// https://source.android.com/docs/compatibility/14/android-14-cdd#227_handheld_media_performance_class
	MediaPerformanceClass_MEDIA_PERFORMANCE_CLASS_14 MediaPerformanceClass = 34
	// As specified in
	// Link pending
	MediaPerformanceClass_MEDIA_PERFORMANCE_CLASS_15 MediaPerformanceClass = 35
)

// Enum value maps for MediaPerformanceClass.
var (
	MediaPerformanceClass_name = map[int32]string{
		0:  "MEDIA_PERFORMANCE_CLASS_UNSPECIFIED",
		-1: "MEDIA_PERFORMANCE_CLASS_INVALID",
		30: "MEDIA_PERFORMANCE_CLASS_11",
		31: "MEDIA_PERFORMANCE_CLASS_12",
		33: "MEDIA_PERFORMANCE_CLASS_13",
		34: "MEDIA_PERFORMANCE_CLASS_14",
		35: "MEDIA_PERFORMANCE_CLASS_15",
	}
	MediaPerformanceClass_value = map[string]int32{
		"MEDIA_PERFORMANCE_CLASS_UNSPECIFIED": 0,
		"MEDIA_PERFORMANCE_CLASS_INVALID":     -1,
		"MEDIA_PERFORMANCE_CLASS_11":          30,
		"MEDIA_PERFORMANCE_CLASS_12":          31,
		"MEDIA_PERFORMANCE_CLASS_13":          33,
		"MEDIA_PERFORMANCE_CLASS_14":          34,
		"MEDIA_PERFORMANCE_CLASS_15":          35,
	}
)

func (x MediaPerformanceClass) Enum() *MediaPerformanceClass {
	p := new(MediaPerformanceClass)
	*p = x
	return p
}

func (x MediaPerformanceClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaPerformanceClass) Descriptor() protoreflect.EnumDescriptor {
	return file_cts_tests_mediapc_requirements_mpc_proto_enumTypes[0].Descriptor()
}

func (MediaPerformanceClass) Type() protoreflect.EnumType {
	return &file_cts_tests_mediapc_requirements_mpc_proto_enumTypes[0]
}

func (x MediaPerformanceClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MediaPerformanceClass) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MediaPerformanceClass(num)
	return nil
}

// Deprecated: Use MediaPerformanceClass.Descriptor instead.
func (MediaPerformanceClass) EnumDescriptor() ([]byte, []int) {
	return file_cts_tests_mediapc_requirements_mpc_proto_rawDescGZIP(), []int{0}
}

var File_cts_tests_mediapc_requirements_mpc_proto protoreflect.FileDescriptor

var file_cts_tests_mediapc_requirements_mpc_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x74, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x6d, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x61, 0x6e, 0x64, 0x72,
	0x6f, 0x69, 0x64, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x65, 0x72, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x6e, 0x63, 0x65, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x2a, 0x8e, 0x02, 0x0a, 0x15, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x23, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x50, 0x45,
	0x52, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x2c, 0x0a,
	0x1f, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x50, 0x45, 0x52, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x4e,
	0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x4d,
	0x45, 0x44, 0x49, 0x41, 0x5f, 0x50, 0x45, 0x52, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x4e, 0x43, 0x45,
	0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x31, 0x31, 0x10, 0x1e, 0x12, 0x1e, 0x0a, 0x1a, 0x4d,
	0x45, 0x44, 0x49, 0x41, 0x5f, 0x50, 0x45, 0x52, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x4e, 0x43, 0x45,
	0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x31, 0x32, 0x10, 0x1f, 0x12, 0x1e, 0x0a, 0x1a, 0x4d,
	0x45, 0x44, 0x49, 0x41, 0x5f, 0x50, 0x45, 0x52, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x4e, 0x43, 0x45,
	0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x31, 0x33, 0x10, 0x21, 0x12, 0x1e, 0x0a, 0x1a, 0x4d,
	0x45, 0x44, 0x49, 0x41, 0x5f, 0x50, 0x45, 0x52, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x4e, 0x43, 0x45,
	0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x31, 0x34, 0x10, 0x22, 0x12, 0x1e, 0x0a, 0x1a, 0x4d,
	0x45, 0x44, 0x49, 0x41, 0x5f, 0x50, 0x45, 0x52, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x4e, 0x43, 0x45,
	0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x31, 0x35, 0x10, 0x23, 0x42, 0x2e, 0x50, 0x01, 0x5a,
	0x2a, 0x63, 0x74, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70,
	0x63, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x6d,
	0x70, 0x63, 0x5f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_cts_tests_mediapc_requirements_mpc_proto_rawDescOnce sync.Once
	file_cts_tests_mediapc_requirements_mpc_proto_rawDescData = file_cts_tests_mediapc_requirements_mpc_proto_rawDesc
)

func file_cts_tests_mediapc_requirements_mpc_proto_rawDescGZIP() []byte {
	file_cts_tests_mediapc_requirements_mpc_proto_rawDescOnce.Do(func() {
		file_cts_tests_mediapc_requirements_mpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_cts_tests_mediapc_requirements_mpc_proto_rawDescData)
	})
	return file_cts_tests_mediapc_requirements_mpc_proto_rawDescData
}

var file_cts_tests_mediapc_requirements_mpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cts_tests_mediapc_requirements_mpc_proto_goTypes = []interface{}{
	(MediaPerformanceClass)(0), // 0: android.media.performanceclass.MediaPerformanceClass
}
var file_cts_tests_mediapc_requirements_mpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cts_tests_mediapc_requirements_mpc_proto_init() }
func file_cts_tests_mediapc_requirements_mpc_proto_init() {
	if File_cts_tests_mediapc_requirements_mpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cts_tests_mediapc_requirements_mpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cts_tests_mediapc_requirements_mpc_proto_goTypes,
		DependencyIndexes: file_cts_tests_mediapc_requirements_mpc_proto_depIdxs,
		EnumInfos:         file_cts_tests_mediapc_requirements_mpc_proto_enumTypes,
	}.Build()
	File_cts_tests_mediapc_requirements_mpc_proto = out.File
	file_cts_tests_mediapc_requirements_mpc_proto_rawDesc = nil
	file_cts_tests_mediapc_requirements_mpc_proto_goTypes = nil
	file_cts_tests_mediapc_requirements_mpc_proto_depIdxs = nil
}
